name: Problem Report
description: Create a problem report to help improve the app
labels: [bug]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search [opened issues](https://github.com/aleksey-hoffman/sigma-file-manager/issues) to see if an issue already exists for this problem.
    options:
    - label: I have searched the opened issues
      required: true
- type: textarea
  attributes:
    label: Problem description
    description: A clear & concise description of what you're experiencing.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps to reproduce
    description: Specify steps to reproduce the behavior.
    value: |
      1. 
  validations:
    required: false
- type: textarea
  attributes:
    label: Environment
    description: |
      Examples:
        - **OS**: Windows 10
        - **App version**: 1.0.0
    value: |
        - OS: 
        - App version: 
  validations:
    required: false
