// SPDX-License-Identifier: GPL-3.0-or-later
// License: GNU GPLv3 or later. See the license file in the project root for more information.
// Copyright © 2021 - present Aleksey Hoffman. All rights reserved.

import type { SigmaExtensionAPI } from '@/modules/extensions/api';

export type ExtensionApiMethodMap = Record<string, (...args: unknown[]) => unknown>;

export function createExtensionApiMethodMap(api: SigmaExtensionAPI): ExtensionApiMethodMap {
  const internalI18n = api.i18n as SigmaExtensionAPI['i18n'] & {
    getLocale?: () => string;
    loadFromPath?: (basePath: string) => Promise<Record<string, Record<string, string>>>;
  };

  return {
    'commands.executeCommand': (...args) => api.commands.executeCommand(args[0] as string, ...args.slice(1)),
    'commands.getBuiltinCommands': () => api.commands.getBuiltinCommands(),
    'context.getCurrentPath': () => api.context.getCurrentPath(),
    'context.getSelectedEntries': () => api.context.getSelectedEntries(),
    'context.getAppVersion': () => api.context.getAppVersion(),
    'context.getDownloadsDir': () => api.context.getDownloadsDir(),
    'context.getPicturesDir': () => api.context.getPicturesDir(),
    'context.openUrl': url => api.context.openUrl(url as string),
    'dialog.openFile': options => api.dialog.openFile(options as never),
    'dialog.saveFile': options => api.dialog.saveFile(options as never),
    'fs.readFile': path => api.fs.readFile(path as string),
    'fs.writeFile': (path, data) => api.fs.writeFile(path as string, data as Uint8Array),
    'fs.readDir': path => api.fs.readDir(path as string),
    'fs.exists': path => api.fs.exists(path as string),
    'fs.downloadFile': (url, path) => api.fs.downloadFile(url as string, path as string),
    'fs.private.readFile': relativePath => api.fs.private.readFile(relativePath as string),
    'fs.private.writeFile': (relativePath, data) => api.fs.private.writeFile(relativePath as string, data as Uint8Array),
    'fs.private.readDir': relativePath => api.fs.private.readDir(relativePath as string | undefined),
    'fs.private.exists': relativePath => api.fs.private.exists(relativePath as string),
    'fs.private.resolvePath': relativePath => api.fs.private.resolvePath(relativePath as string),
    'fs.storage.readFile': relativePath => api.fs.storage.readFile(relativePath as string),
    'fs.storage.writeFile': (relativePath, data) => api.fs.storage.writeFile(relativePath as string, data as Uint8Array),
    'fs.storage.readDir': relativePath => api.fs.storage.readDir(relativePath as string | undefined),
    'fs.storage.exists': relativePath => api.fs.storage.exists(relativePath as string),
    'fs.storage.resolvePath': relativePath => api.fs.storage.resolvePath(relativePath as string),
    'fs.storage.importFile': (sourcePath, targetRelativePath) => api.fs.storage.importFile(sourcePath as string, targetRelativePath as string),
    'fs.storage.deleteFile': relativePath => api.fs.storage.deleteFile(relativePath as string),
    'fs.scoped.requestDirectoryAccess': options => api.fs.scoped.requestDirectoryAccess(options as never),
    'fs.scoped.getDirectories': () => api.fs.scoped.getDirectories(),
    'fs.scoped.readFile': path => api.fs.scoped.readFile(path as string),
    'fs.scoped.writeFile': (path, data) => api.fs.scoped.writeFile(path as string, data as Uint8Array),
    'fs.scoped.readDir': path => api.fs.scoped.readDir(path as string),
    'fs.scoped.exists': path => api.fs.scoped.exists(path as string),
    'ui.showNotification': options => api.ui.showNotification(options as never),
    'ui.showDialog': options => api.ui.showDialog(options as never),
    'ui.copyText': text => api.ui.copyText(text as string),
    'ui.clipboardWrite': items => api.ui.clipboardWrite(items as Record<string, Uint8Array>[]),
    'ui.input': options => api.ui.input(options as never),
    'ui.select': options => api.ui.select(options as never),
    'ui.checkbox': options => api.ui.checkbox(options as never),
    'ui.textarea': options => api.ui.textarea(options as never),
    'ui.separator': () => api.ui.separator(),
    'ui.text': content => api.ui.text(content as string),
    'ui.alert': options => api.ui.alert(options as never),
    'ui.image': options => api.ui.image(options as never),
    'ui.previewCard': options => api.ui.previewCard(options as never),
    'ui.previewCardSkeleton': () => api.ui.previewCardSkeleton(),
    'ui.skeleton': options => api.ui.skeleton(options as never),
    'ui.button': options => api.ui.button(options as never),
    'ui.showModal': options => api.ui.showModal(options as never),
    'shell.run': (commandPath, args) => api.shell.run(commandPath as string, args as string[] | undefined),
    'shell.renamePartFilesToTs': directory => api.shell.renamePartFilesToTs(directory as string),
    'settings.get': key => api.settings.get(key as string),
    'settings.set': (key, value) => api.settings.set(key as string, value),
    'settings.getAll': () => api.settings.getAll(),
    'settings.reset': key => api.settings.reset(key as string),
    'storage.get': key => api.storage.get(key as string),
    'storage.set': (key, value) => api.storage.set(key as string, value),
    'storage.remove': key => api.storage.remove(key as string),
    'path.dirname': filePath => api.path.dirname(filePath as string),
    'path.basename': (filePath, suffix) => api.path.basename(filePath as string, suffix as string | undefined),
    'path.extname': filePath => api.path.extname(filePath as string),
    'runtime.isExtensionInstallCancelledError': error => api.runtime.isExtensionInstallCancelledError(error),
    'platform.joinPath': (...segments) => api.platform.joinPath(...segments as string[]),
    'platform.getOs': () => api.platform.os,
    'platform.getArch': () => api.platform.arch,
    'platform.getPathSeparator': () => api.platform.pathSeparator,
    'platform.getIsWindows': () => api.platform.isWindows,
    'platform.getIsMacos': () => api.platform.isMacos,
    'platform.getIsLinux': () => api.platform.isLinux,
    'binary.ensureInstalled': (id, options) => api.binary.ensureInstalled(id as string, options as never),
    'binary.getPath': id => api.binary.getPath(id as string),
    'binary.isInstalled': id => api.binary.isInstalled(id as string),
    'binary.remove': id => api.binary.remove(id as string),
    'binary.getInfo': id => api.binary.getInfo(id as string),
    'i18n.t': (key, params) => api.i18n.t(key as string, params as never),
    'i18n.mergeMessages': messages => api.i18n.mergeMessages(messages as never),
    'i18n.mergeFromPath': basePath => api.i18n.mergeFromPath(basePath as string),
    'i18n.extensionT': (key, params, fallback) => api.i18n.extensionT(key as string, params as Record<string, string | number> | undefined, fallback as string | undefined),
    'i18n.getLocale': () => internalI18n.getLocale?.() ?? 'en',
    'i18n.loadFromPath': basePath => internalI18n.loadFromPath?.(basePath as string) ?? Promise.resolve({}),
  };
}
